### ISSUE TITLE
Live Demo failed to load source map

### ISSUE THREAD

**Issue by bzzzggz** [pwa-builder/pwa-update#16] opened 2020-08-06 08:01 UTC
**Describe the bug**
When I open the live demo, and check Dev tools in Edge, got this error message:
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/@pwabuilder/pwa-update.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Same error happens on my own web app.

Fixed by change the following:

importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.0.0/workbox-sw.js');

**Comment by nmetulev** [comment] 2022-04-19 16:23
Duplicate of https://github.com/pwa-builder/PWABuilder/issues/2799

**Closed by nmetulev** 2022-04-19 16:23 UTC
